[profile.default]
src = "src"
out = "out"
libs = ["dependencies"]

[lint]
exclude_lints = [
    "mixed-case-variable",
    "screaming-snake-case-immutable",
    "mixed-case-function",
    "unsafe-typecast",
    "divide-before-multiply",
    "erc20-unchecked-transfer",
    "screaming-snake-case-const",
    "unsafe-cheatcode",
]

[dependencies]
forge-std = "1.11.0"

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
